### ISSUE TITLE
[FIX] 공유 - 친구 목록 QA

### ISSUE THREAD

**Issue by onpyeong** [TeamSobokSobok/Sobok-Android#110]
## Description
공유 - 친구목록 QA

## To-do
- [x] 친구 목록 간격 조정
- [x] 스크롤 시 친구 이름 안보이도록 수정
- [x] 공유 요청 엠티뷰 행간
- [x] 공유 요청 엠티뷰 버튼 높이
- [x] 친구 이름 수정 아이콘 위치
- [x] 친구 이름 수정 서버 연결
