### ISSUE TITLE
[FEAT] 설정 디자인 수정사항 및 QA

### ISSUE THREAD

**Issue by onpyeong** [TeamSobokSobok/Sobok-Android#122]
## Description
설정 디자인 수정사항 및 QA

## To-do
- [x] 약정보가 제대로 뜨는가?
- [ ] 툴팁
- [x] 엠티뷰
- [x] 내 닉네임 수정이 바로 반영 되는가?
- [x] 오류 체크 (특수문자, 10자, 2자, 띄어쓰기 비허용)
- [x] 중복확인, 이미 사용중, 사용가능
- [ ] 이메일, 이용약관, 오픈소스
- [x] 회원탈퇴 디자인 수정사항
- [ ] 밑에서 올라오는 뷰
