### ISSUE TITLE
[FEAT] 로그인, 회원가입 디자인 수정사항 및 QA

### ISSUE THREAD

**Issue by onpyeong** [TeamSobokSobok/Sobok-Android#124]
## Description
로그인, 회원가입 디자인 수정사항 및 QA

## To-do
- [x]  소셜 로그인이 잘 되는가?
- [x]  자동로그인이 되는가?
- [x]  로그아웃이 되는가?
- [x]  회원탈퇴가 되는가?
- [x]  회원가입이 잘 되는가?
- [x]  이용약관 뷰 뜨는지
- [x]  회원가입 시 화면 진입에 문제가 없는가?
- [x] 로그아웃 & 회원탈퇴 스낵바
- [x] 디자인 변경사항
