### ISSUE TITLE
[FEAT] 공유 탭 - 스티커 보내기

### ISSUE THREAD

**Issue by visionWWW** [TeamSobokSobok/Sobok-Android#132]
## Description
공유 탭 - 스티커 보내기 관련 

## To-do
- [x] [UI] 스티커 보내기 다이얼로그
- [x] [FEAT] 스티커 보내기 다이얼로그
- [x] [NETWORK] 스티커 보내기 다이얼로그
- [x] [UI] 스티커 보기 바텀 시트
- [x] [FEAT] 스티커 보기 바텀 시트
- [x] [NETWORK] 스티커 보기 바텀 시트
