### ISSUE TITLE
[FIX] 설정 QA

### ISSUE THREAD

**Issue by onpyeong** [TeamSobokSobok/Sobok-Android#138]
## Description
설정 QA

## To-do
- [ ] 약관 및 정책 → 회원가입 & 설정 링크 연결
- [ ] 유저 이름 수정
- [ ] 설정 - 내 약 화살표 클릭되도록
- [ ] 설정 - 친구 삭제 요청하기 추가
- [ ] 설정 - 이메일로 요청하기 (기종, OS, 버전 포함)
