### ISSUE TITLE
[FIX] 계정 추가 QA

### ISSUE THREAD

**Issue by onpyeong** [TeamSobokSobok/Sobok-Android#140]
## Description
계정 추가 QA

## To-do
- [x] 계정추가 요청 시, 상대방이 수락 안 했을 경우 토스트 메시지 ‘이미 친구를 신청 했어요’로 수정
- [ ]  본인 요청 토스트 메세지 수정
- [x]  닉네임 없을 경우 로직 수정
- [x]  5명 이상일 시 설정>친구 삭제 요청으로 텍스트 변경
