### ISSUE TITLE
[FIX] 캘린더 QA

### ISSUE THREAD

**Issue by onpyeong** [TeamSobokSobok/Sobok-Android#142]
## Description
캘린더 QA

## To-do
- [x] 오늘 날짜 약 체크 시 안보임
- [x] 다른 날짜 한 번 눌러야 반영됨
- [x]  공유 캘린더 - 멤버 이름 전환 시 바로 반영 안됨
- [x]  공유 캘린더 - 공유탭 진입 시 바로 반영 안됨
- [x]  공유 캘린더 - 여러번 호출되는 문제
