### ISSUE TITLE
[FIX] 약추가 QA

### ISSUE THREAD

**Issue by visionWWW** [TeamSobokSobok/Sobok-Android#147]
## Description
약추가 QA

## To-do
1순위
- [ ]  약추가 탭 (+) 2번 클릭 시 다시버튼 누를때 오류
- [ ]  약 추가 완료 후, 약 추가 바텀시트 닫고 홈 버튼 보이도록 수정
2순위
- [ ]  멘트 수정
- [ ]  약 추가 시간 정렬… 아마 안할듯
- [ ]  약 시간 최소 1개 이상 → 0개도 가능하게 수정
