### ISSUE TITLE
[FIX] 약추가 - 약이름 키보드 오류 수정

### ISSUE THREAD

**Issue by visionWWW** [TeamSobokSobok/Sobok-Android#162]
## Description
키보드 바깥 누르면 내려가기
엔터누르면 내려가기

## To-do
- [x] 키보드 오류 수정
- [x] 약이름 메시지 수정
- [x] 약추가 로딩뷰 설정
- [x] 내약목록 -> 수정시 다시 내약목록으로 돌아오게 수정
