### ISSUE TITLE
[FIX] 약개수 오류 수정

### ISSUE THREAD

**Issue by visionWWW** [TeamSobokSobok/Sobok-Android#173]
## Description
약관련 이모저모

## To-do
- [ ] 약추가 개수 오류
- [ ] 약삭제 화면 중복 오류
- [ ] 로딩창 교환
- [ ] 로딩화면 곳곳에 붙이기
