### ISSUE TITLE
[FEAT] 내 정보

### ISSUE THREAD

**Issue by onpyeong** [TeamSobokSobok/Sobok-Android#61]
## Description
내 정보 UI & 서버 연결

## To-do
- [x] 내 약 관리 UI
- [x] 이름 수정 UI
- [x] 내 약 관리 서버 연결
- [x] 이름 수정 & 중복 체크 서버 연결
- [ ] 이름 수정 서버 연결하기
