### ISSUE TITLE
[FEAT] 주간 캘린더 연결

### ISSUE THREAD

**Issue by onpyeong** [TeamSobokSobok/Sobok-Android#77]
## Description
주간 캘린더 연결 및 캘린더 코드 수정

## To-do
- [ ] 캘린더 오늘 날짜 UI 수정
- [ ] 캘린더 viewmodel 코드 수정
- [ ] 주간 캘린더 연결
