### ISSUE TITLE
[FIX] 알림뷰 이슈 해결

### ISSUE THREAD

**Issue by garden0401** [TeamSobokSobok/Sobok-Android#78]
## Description
리사이클러뷰 구조 개선

## To-do
- [ ] 데이터 부분 갱신으로 변경 -> 버벅임 해결방법 시도
- [ ] 툴팁 적용
- [ ] 알림뷰 에러처리-> 약5개 이상일 떄
- [x] 알림뷰 친구수락 안되는 이슈 해결
- [x] 알림뷰 시간 정보 포맷팅
- [x] 알림뷰 타인에게 받은 약 정보 시간 포맷팅
