### ISSUE TITLE
[FEAT] 홈/공유 약리스트 버전 1.0 반영

### ISSUE THREAD

**Issue by garden0401** [TeamSobokSobok/Sobok-Android#81]
## Description
홈/공유 약리스트 릴리즈 버전 1.0 반영
## To-do
- [x] 홈/공유 약리스트 UI
- [x] 홈/공유 기능
- [x] Empty view 추가
- [x] 복용 체크/체크 취소 기능

**Comment by garden0401** [comment]
완완~!
