### ISSUE TITLE
[FIX] 설정 디자인 QA

### ISSUE THREAD

**Issue by onpyeong** [TeamSobokSobok/Sobok-Android#86]
## Description
설정 디자인 QA

## To-do
- [ ] 내 약 관리 폰트 변경
- [ ] 설정 화살표 수직 마진 변경
- [ ] 툴팁 화살표 위치
- [ ] 툴팁 바깥 누르면 사라지기
