### ISSUE TITLE
[FIX] 공유 요청 QA

### ISSUE THREAD

**Issue by onpyeong** [TeamSobokSobok/Sobok-Android#91]
## Description
공유 요청 QA

## To-do
- [x] 돋보기 아이콘 변경
- [x] 화면 진입 시 글자 수 안뜨도록 수정
- [x] 글자가 1글자이고 특수문자인 경우 -> 특수문자 불가능 메시지
- [x] 검색창 focus == true & text는 null인 경우에 x버튼 비활성화
